matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            libx11-dev
            libgtk2.0-dev
            libcanberra-gtk-module
            mingw-w64
      language: node_js
      sudo: false
      node_js:
        - "node"
      script:
        - npm run-script oneOff
    - os: osx
      osx_image: xcode9.4
      language: node_js
      sudo: false
      node_js:
        - "node"
      script:
        - npm run-script oneOff
